Refactor timers and fix temporary loops
ni/mstpd pull request #1
Opened 2023-12-01 20:09 UTC by ErikHons

The concept here is to replace the "tick" based port timers with timerfds so that the changes they drive occur close to actual seconds when network peers would expect them. In particular, the auto edge transition could occur in only two seconds an occasionally beat a peers hello time resulting in a temporary loop.

This likely fixes issue https://github.com/mstpd/mstpd/issues/100

2023-12-01 21:21 UTC, bstreiff requested changes
commit structure:

- commit "add epoll support and callbacks for timerfds"
   - This commit seems to be doing a couple things at once and it may make more sense to split it:
      - you've got the introduction of a `timer_expired` concept
      - and you've got the introduction of timerfd-based timers
- commit "mstpd: use timerfd for edge transition timer"
   - seems fine?
- both commits probably need a `Signed-off-by:`, it looks like they generally do that upstream.

overall:

Why does taking edgeDelayWhile out of the state machine and making it its own timerfd fix the bug? It _looks_ like your second commit is largely doing replacements of the form:
```
unsigned int meow         -> struct epoll_event_handler meow; epoll_timer_init(&meow);
assign(meow, initialTime) -> epoll_timer_start(&meow, initialTime);
meow != initialTime       -> epoll_timer_active(&meow);
0 == meow                 -> epoll_timer_expired(&meow);
```

Would it be more sensible to change epoll_main_loop to be triggered on a timerfd so that the entire state machine advances monotonically? (The way that [it tries to guess the next timeout](https://github.com/ni/mstpd/blob/c216c5da74c8a5aec4ad1ed4a0b37a7016acb320/epoll_loop.c#L119) feels a bit dodgy to me...) It sort of feels like either 1) all timers should be their own timerfds (and then we don't really have an explicitly-`tick`-defined state machine anymore), or 2) the state machine needs to be timerfd-driven.

2023-12-01 21:21 UTC, bstreiff commented on mstp.c
> +       timing between peers (e.g. for edge transitions).
```c
/* This seems to differ from the comment
 * style elsewhere in this file, which
 * looks more like this and thus should
 * probably match it.
 */
```

2023-12-01 21:21 UTC, bstreiff commented on epoll_loop.c
> +    // If the timer isn't readble for any reason, assume it is still
readable

2023-12-01 21:21 UTC, bstreiff commented on epoll_loop.c
> +    return current_value.it_value.tv_sec > 0 || current_value.it_value.tv_nsec > 0;
I think this logic is correct, but I think I'd prefer to see this as:

```c
return !(current_value.it_value.tv_sec == 0 && current_value.it_value.tv_nsec == 0);
```
because doing relative compares on the `tv_sec` and `tv_nsec` fields of a `struct timespec` independently always puts me on edge.

(I wish libc just came with a suite of equality and relative-compare functions for `struct timespec` instead of everyone having to poke at the fields...)

[edit: actually I guess there is already a `time_diff` in epoll_loop.c, maybe wrap this into a `time_zero`?]

2023-12-01 21:21 UTC, bstreiff commented on mstp.c
> -    if(prt->edgeDelayWhile)
Taking edgeDelayWhile out of the state machine `tick` seems a little weird to me (will elaborate in summary)

2023-12-04 17:38 UTC, ErikHons commented
> * commit "add epoll support and callbacks for timerfds"
>   
>   * This commit seems to be doing a couple things at once and it may make more sense to split it:
>     
>     * you've got the introduction of a `timer_expired` concept
>     * and you've got the introduction of timerfd-based timers

That's a great idea. On it.

> * both commits probably need a `Signed-off-by:`, it looks like they generally do that upstream.

Roger wilco.

> Why does taking edgeDelayWhile out of the state machine and making it its own timerfd fix the bug?

The comment in MSTP_IN_timer_expired() addresses that. My rough idea is to get buy-in upstream to replace all the tick-based stuff with timerfds and remove the comment at that time. As you noted, I would create separate commits for each replacement.

> Would it be more sensible to change epoll_main_loop to be triggered on a timerfd so that the entire state machine advances monotonically?

The crux of the issue is that the events being timed aren't all one-second-tick aligned. To use a single timerfd you would have to track the expiry of each and calculate the next time. Using separate timerfds makes it the kernel's problem! So I acknowledge your either-or and separate timerfds is what I'm going for.

2023-12-04 17:38 UTC, ErikHons commented on mstp.c
> +       timing between peers (e.g. for edge transitions).
Huh, you are right

2023-12-04 17:38 UTC, ErikHons commented on epoll_loop.c
> +    // If the timer isn't readble for any reason, assume it is still
tyyping is hard

2023-12-04 17:43 UTC, ErikHons commented on epoll_loop.c
> +    return current_value.it_value.tv_sec > 0 || current_value.it_value.tv_nsec > 0;
The docs for "timerfd_gettime" say "If both fields of this structure are zero, then the timer is currently disarmed." I figure I should follow that as close as possible which reinforces your relative compare point.

2023-12-06 20:59 UTC, bstreiff commented
All three commits probably still need `Signed-off-by`s, and the commits themselves could probably use a bit more elaboration in their descriptions (the first two are just subject lines)

Should we be targeting this into an `ni/master` branch or a versioned branch or something instead of `master`?

2023-12-12 02:21 UTC, ErikHons commented
The latest commits incorporate Brenda's feedback and also fix a bug in the timer code

2023-12-12 15:57 UTC, bstreiff approved these changes
LGTM

2023-12-12 19:23 UTC, ErikHons commented
[0]     Erik Hons reacted to your message:
________________________________
From: bstreiff ***@***.***>
Sent: Tuesday, December 12, 2023 3:57:40 PM
To: ni/mstpd ***@***.***>
Cc: Erik Hons ***@***.***>; Assign ***@***.***>
Subject: Re: [ni/mstpd] Refactor timers and fix temporary loops (PR #1)


@bstreiff approved this pull request.

LGTM

—
Reply to this email directly, view it on GitHub<https://github.com/ni/mstpd/pull/1#pullrequestreview-1777869737>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AEVLXFCFQLH4VQQEJNDDMDDYJB5HJAVCNFSM6AAAAABADK4IZ2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTONZXHA3DSNZTG4>.
You are receiving this because you were assigned.Message ID: ***@***.***>

2023-12-12 19:23 UTC, ErikHons commented
[heart]         Erik Hons reacted to your message:
________________________________
From: bstreiff ***@***.***>
Sent: Tuesday, December 12, 2023 3:57:40 PM
To: ni/mstpd ***@***.***>
Cc: Erik Hons ***@***.***>; Assign ***@***.***>
Subject: Re: [ni/mstpd] Refactor timers and fix temporary loops (PR #1)


@bstreiff approved this pull request.

LGTM

—
Reply to this email directly, view it on GitHub<https://github.com/ni/mstpd/pull/1#pullrequestreview-1777869737>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AEVLXFCFQLH4VQQEJNDDMDDYJB5HJAVCNFSM6AAAAABADK4IZ2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTONZXHA3DSNZTG4>.
You are receiving this because you were assigned.Message ID: ***@***.***>

2023-12-12 21:19 UTC, merged